"""initial schema

Revision ID: a44afd613d14
Revises:
Create Date: 2026-09-13 08:33:15.072434
"""
from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision = 'a44afd613d14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_categories',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'MANAGER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('manager_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('recipient_id', app.db.types.GUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_recipient_unread', 'notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_table('requests',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', app.db.types.GUID(), nullable=True),
    sa.Column('requester_id', app.db.types.GUID(), nullable=False),
    sa.Column('assignee_id', app.db.types.GUID(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='request_priority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['request_categories.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_assignee_id'), 'requests', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_requests_requester_id'), 'requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index('ix_requests_status_priority', 'requests', ['status', 'priority'], unique=False)
    op.create_table('request_assignments',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('request_id', app.db.types.GUID(), nullable=False),
    sa.Column('assignee_id', app.db.types.GUID(), nullable=False),
    sa.Column('assigned_by_id', app.db.types.GUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_assignments_request_id'), 'request_assignments', ['request_id'], unique=False)
    op.create_table('request_comments',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('request_id', app.db.types.GUID(), nullable=False),
    sa.Column('author_id', app.db.types.GUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_comments_request_id'), 'request_comments', ['request_id'], unique=False)
    op.create_table('request_status_history',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('request_id', app.db.types.GUID(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='request_status'), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='request_status'), nullable=False),
    sa.Column('changed_by_id', app.db.types.GUID(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_status_history_request_id'), 'request_status_history', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_status_history_request_id'), table_name='request_status_history')
    op.drop_table('request_status_history')
    op.drop_index(op.f('ix_request_comments_request_id'), table_name='request_comments')
    op.drop_table('request_comments')
    op.drop_index(op.f('ix_request_assignments_request_id'), table_name='request_assignments')
    op.drop_table('request_assignments')
    op.drop_index('ix_requests_status_priority', table_name='requests')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_requester_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_assignee_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index('ix_notifications_recipient_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('request_categories')
    # ### end Alembic commands ###
